[package]
name = "sel4_ipc"
version = "0.1.0"
edition = "2021"

[dependencies]
sel4_common = { git = "https://github.com/rel4team/sel4_common.git", branch = "feature/test-check" }
sel4_cspace = { git = "https://github.com/rel4team/sel4_cspace.git", branch = "feature/test-check" }
sel4_vspace = { git = "https://github.com/rel4team/sel4_vspace.git", branch = "feature/test-check" }
sel4_task = { git = "https://github.com/rel4team/sel4_task.git", branch = "feature/test-check" }
unimock = { version = "0.6.6", default-features = false, features = ["critical-section"] }
buddy_system_allocator = "0.10.0"

[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu = "9.3"
tock-registers = "0.8"

[features]
unit-test = ["sel4_common/unit-test"]
default = ["unit-test"]
